### ISSUE TITLE
🐛Not CD, Blu-ray, DVD or Data. Bailing out on sr0

### ISSUE THREAD

**Issue by BlakeDarrow** [ahnooie/automatic-ripping-machine#1417]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### I have checked the wiki

- [x] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [x] I'm using the latest release

### Describe the bug?

No matter how I setup this docker image (latest) I get the following:

"Not CD, Blu-ray, DVD or Data. Bailing out on sr0"

My drive works with MakeMKV and the DVD is also confirmed to work and rip windows MakeMKV install. I have the proper Optical Drive dev path provided: /dev/sr0 but nothing works. Any help would be greatly appreciated. All my datasets have permissions setup, and no errors related to them are ever printed.

Using TrueNAS and the community latest image of automatic-ripping-machine.

### To Reproduce

1. With TrueNAS installed select "Discover Apps"
2. Search for "Automated Ripping Machine" 
3. Install
4. Create required datasets and set preset as "apps"
5. Start the Docker
6. Insert DVD
7. Notice "Not CD, Blu-ray, DVD or Data. Bailing out on sr0" in docker logs

### What OS are you seeing the problem on?

Other (please state in Anything else? section)
TrueNAS 25.04.1

### ARM Release Version or Git hash (You can find this in the arm settings page)
v2.15.1

### Expected behavior?

DVD gets ripped successfully. 

### Relevant log output

```shell
"""
2025-06-11 03:30:16.899384+00:00[2025-06-11 03:30:16,899] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
2025-06-11 03:30:23.730349+00:00Jun 11 03:30:23 acaf18569cf1 ARM: [ARM] Entering docker wrapper
2025-06-11 03:30:23.745025+00:00Jun 11 03:30:23 acaf18569cf1 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
2025-06-11 03:30:24.051169+00:00[2025-06-11 03:30:24,050] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
"""
```

### Anything else?

My drive IS found in the web interface, and even selecting "Manual" on the drive UI outputs the same error.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by johnwinward** [comment]
I believe I has this same issue a little while ago. I am also on TrueNAS.

I had external USB DVD drive, and I passed /dev/sr0 to the container. I was able to get my drive working by also passing in /dev/sg7 in addition to /dev/sr0. If you go to the TrueNAS shell and run `sudo sg_map`, you should be able to map which sg goes with sr0. It might not be sg7. I am not sure exactly why I had to do this, I'm new to using TrueNAS and ARM, but hopefully that works for you as well.

**Comment by lmann4** [comment]
I'm running into the same issues with but only for Blurays in a Verbatim 43888 USB drive plugged into my ubuntu server. The system's SATA optical drive and the USB drive runs no problem with DVDs. The USB drive is recognized by ARM using `/dev/sr1`, but inserting a blu ray results in the error mentioned above.

**Comment by lmann4** [comment]
Mapping the drive with `sg` insted of `sr` like @johnwinward suggested along with flashing my USB drive with the appropriate firmware seems to have worked.
My Verbatim 43888 is one of the newer ones that comes with LG BU40N internals and so following this guide for the LG BU40N worked to flash it.
https://forum.makemkv.com/forum/viewtopic.php?f=16&t=19634

**Comment by gteltschik** [comment]
Adding the sg devices should get this working. I was having similar problems, but i noticed they only started when I changed my mode to "backup." if you look into the code when it starts makemkv, it uses the "disc:" switch when the mode is backup, and the "dev:" switch for other modes. 

Following this line of thinking led me to [https://github.com/jlesage/docker-makemkv?tab=readme-ov-file#access-to-optical-drives](url) where there is a long explanation that eventually summarizes to:

"This indicates that /dev/sr0 and /dev/sg3 need to be exposed to the container."

In the example, /dev/sr0 and /dev/sg3 are the same device as exposed by the 'lsscsi -g' command. In my system, it is sr0/sg0, sr1/sg1, etc., so I had to modify my docker start code to have:

--device="/dev/sr0:/dev/sr0" \
--device="/dev/sg0:/dev/sg0" \
--device="/dev/sr1:/dev/sr1" \
--device="/dev/sg1:/dev/sg1" \

Once I rebuilt/restarted the container, it started working with no other changes. I didn't switch it our of backup mode to confirm it does not affect anything else, but I imagine it will continue working as before.  (If not, then I'd just need two different start commands.)

In summary, either the script needs to be modifed to not use the drive switch in backup mode (if such a thing is possible), or the docker installation instructions need to be updated to include the need to also pass the sgx devices to the container (so that you have two entries for each drive, not one).

**Comment by microtechno9000** [comment]
Seems that the `sg` device is not always passed through, or available from the host
Depends on the host system, drivers loaded and if using 'privileged'

Will look into what we can do from within ARM to flag this, or check prior to running a job.
Any thoughts welcome

**Comment by polskikrol** [comment]
I had the same problem, and this is all the result of how MakeMKV handles CR-ROM drives: https://forum.makemkv.com/forum/viewtopic.php?t=16939&start=30.

I am testing a few more things, but even if a docker container has to run in privileged mode or is restricted by a NAS implementation, the following appears to work:

```
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg1:/dev/sg1
      - /dev/bus/usb:/dev/bus/usb # May not be needed, will test.
      - /dev/dri:/dev/dri # Needed for Intel QSV
```

The following I am currently testing as well in terms of security options required (if any):

```
    privileged: false
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    security_opt:
      - apparmor=unconfined
```

For now, I have it ripping in a privileged container with the above config, but will whittle this down to see what bare minimum is.

@microtechno9000 The latest release has reworked code for identifying the drives. Would it make sense to have ARM perform an access test (basically the functions of how MakeMKV access the drive) and provide a status within Settings -> Disk Drives? For example, the same like we have with hardware acceleration, a status with icon... if it is not available/ready, maybe a hover over text with some documentation to make sure you are passing correct devices (or a link to docs).

**Comment by microtechno9000** [comment]
@polskikrol thats a great idea, feel free to start working on that.

I have been thinking of how I could add some kind of "is ARM ready" check in. That would be a good check

**Comment by polskikrol** [comment]
Ok, so after much tinkering, and barring a few odd bugs with jobs on the newest release, have a good solid dockerfile for Intel QSV.

```
services:
  arm:
    container_name: 'arm'
    hostname: 'arm'
#    user: '2002:2002'
    group_add:
      - '24' # cdrom
      - '44' # video
      - '109' # render
    networks:
      docker_bridge:
        ipv4_address: '172.16.0.2'
    environment:
      - ARM_UID=2002
      - ARM_GID=2002
      - TZ='America/New_York'
    volumes:
      - /docker/arm/files/arm:/home/arm
      - /docker/arm/files/config:/etc/arm/config
    devices:
      - /dev/sr0:/dev/sr0 # cdrom (standard CD-ROM access and mounting)
      - /dev/sg1:/dev/sg1 # cdrom (low-level SCSI command access)
      - /dev/dri:/dev/dri # hardware transcode
    ports:
      - '8080:8080' # port for web interface (HTTP)
    privileged: false 
    restart: 'unless-stopped'
    build:
      context: '/docker/arm'
      dockerfile_inline: |
        FROM automaticrippingmachine/automatic-ripping-machine:latest AS base
        LABEL org.opencontainers.image.description="ARM w/ Intel Quick Sync Video Support (Intel Media Stack)"
        RUN apt update -y &&\
          apt upgrade -y &&\
          apt install -y intel-media-va-driver-non-free libigdgmm12 &&\
          cd /tmp &&\
          mkdir -p quicksync && cd quicksync &&\
          git clone https://github.com/Intel-Media-SDK/MediaSDK msdk &&\
          mkdir -p build-msdk && cd build-msdk &&\
          cmake ../msdk &&\
          make && make install &&\
          cd ../.. &&\
          rm -r quicksync &&\
          chmod 755 -R /opt/arm/arm/ripper
      no_cache: true
networks:
  docker_bridge:
    external: true
```

From a docker perspective, the only thing I dont like is that the docker image runs as root. In terms of permissions and code, running this with the 'user' directive will fail. At some point will figure out how to make it run.

Important thing.... you can run as privileged: false, a restriction with many 3rd party docker solutions, without needing to much with cap-add or apparmor, as long as you pass BOTH a) sr and b) sg cdrom devs. Otherwise MakeMKV will fail.
